### ISSUE TITLE
IE8

### ISSUE THREAD

**Issue by agentcooper** [bitinn/vdom-parser#7]
Hey.

How much work would it currently take to support IE8?

**Comment by bitinn** [comment]
I remember seeing a few issues when running it on saucelabs IE8, which is why I didn't include it.

But the best way for you to verify is to run the testcases locally on an actual IE8, see package.json for test commands (generally speaking innerHTML should be compatible with most tags under body, as long as it doesn't throw errors, the diff/patch process will take care of the minor difference in vdom).

**Comment by niksy** [comment]
I’ve just tried it in IE8, and first issue I’ve encountered is related to `style` attribute parsing where it doesn’t apply any styles in IE8, as opposed to [`vdom-virtualize`](https://github.com/marcelklehr/vdom-virtualize/) which displays everything correctly (probably because it uses native style parsing).

Plus, there is issue of using `forEach` on arrays which isn’t supported in IE8, as well as other ES5 methods such as `String.prototype.trim`; `DOMParser` is instantiated at start and it requires that polyfill is available, but provided polyfill doesn’t attach itself to `window.DOMParser` so even if you include it, it won’t do anything.
